server:
  port: 0
 
spring:
  data:
    mongodb:
      database: data
      host: localhost
      port: 27017
  cloud:
    config:
      uri: http://localhost:8765

       
  application:
    name: todo-service